- src/gatsby-node.js
Cleaned up the code, refactored the the functions and added helpers.
It's now a basic working prototype.
@datakurre I'm not sure how often I should update the changelog? I'll do that every week just adding all the changes made?
> Clean up code, add helpers, basic traversal

- .travis.yml
- shell.nix
Once this works, fixes https://github.com/collective/gatsby-source-plone/issues/6
But @tisto should enable gh-pages from gh-pages branch at first
> Enable gh-pages deploy

- .travis.yml
- Makefile
- shell.nix
- src/gatsby-node.js
- tests/gatsby-starter-default/Makefile
- tests/gatsby-starter-default/fixture/contact.json
- tests/gatsby-starter-default/fixture/export.sh
- tests/gatsby-starter-default/fixture/gatsby-source-plone.json
- tests/gatsby-starter-default/fixture/import.sh
- tests/gatsby-starter-default/fixture/purge.sh
- tests/gatsby-starter-default/test.robot
* export.sh export pages from Plone root
* purge.sh clear site from all content
* import.sh imports pages to Plone root (in exported order by modification date order)
* make populate replaces site content with exported test data
> Add initial (flat) test fixture population

- docs/plugin_options.md
- src/gatsby-node.js
- tests/gatsby-starter-default/gatsby-config.js
Changes pending, currently in discussion at ref: #48 
Code refactored, logs added.
> Full @search traversal

- .travis.yml
- tests/gatsby-starter-default/gatsby-node.js
- tests/gatsby-starter-default/src/pages/index.js
- tests/gatsby-starter-default/src/templates/page.js
- tests/gatsby-starter-default/test.robot
> Fix gh-pages index page [fixes #52]

- tests/gatsby-starter-default/src/pages/index.js
> Fix issue where contents listing links were broken with path-prefix

- package.json
> Add repository field for Gatsby site to find README

- src/gatsby-node.js
Fixes #67 
Loops through batching and piles up data allowing Plone sites of any size of content objects to be traversed.
> Resolve pagination in @search traversal

- src/gatsby-node.js
- tests/gatsby-starter-default/.gitignore
- tests/gatsby-starter-default/gatsby-config.js
- tests/gatsby-starter-default/package.json
- tests/gatsby-starter-default/yarn.lock
Addresses #56 
Right now I've just added support for authorization in the plugin and also .env config in `gatsby-starter-default`. If this is good to go, we can move on to the documentation.
> Authorization support for plugin

- docs/authentication.md
- docs/plugin_options.md
I've added documentation for authentication and updated plugins docs based on our discussion in #69
> Authentication documentation

- docs/tree-hierarchy.md
Added some basic documentation for tree hierarchy.
> Add tree hierarchy docs

- src/gatsby-node.js
Fixes #75 
Filter out the base node from @search list, preventing creation of 2 nodes of same data.
> Fix subsite issue

- src/gatsby-node.js
- tests/gatsby-starter-default/gatsby-node.js
References #71 
Added support for plugin to handle expansions.
> Add expansions support in plugin

- docs/expansions.md
- docs/plugin_options.md
> Add basic documentation for Expansions

- src/gatsby-node.js
Attempting to fix the GraphQL issue discussed in #82 
Will try and improve code quality by abstracting it into a function once this works fine.
> Fix GraphQL querying issue

- src/gatsby-node.js
- tests/gatsby-starter-default/gatsby-node.js
- tests/gatsby-starter-default/src/components/Breadcrumbs.js
- tests/gatsby-starter-default/src/components/Document.js
- tests/gatsby-starter-default/src/components/Folder.js
- tests/gatsby-starter-default/src/components/NewsItem.js
- tests/gatsby-starter-default/src/components/PloneSite.js
- tests/gatsby-starter-default/src/styles/bootstrap.scss
- tests/gatsby-starter-default/src/templates/default.js
- tests/gatsby-starter-default/test.robot
References #82 
Gatsby plugin now supports expansions, this PR updates the tests/gatsby-starter-default to showcase the new feature.
> Add example in gatsby-site for Breadcrumbs

- src/gatsby-node.js
Addresses  #29 
Basic traversal and node creation established with BFS algorithm. Right now I haven't yet implemented handling `searchParams` it just checks it for deciding which method to use.
> Basic recursive approach

- docs/recursive_traversal.md
> Add docs for recursive traversal

- src/gatsby-node.js
I've taken the case that searchParams is an object of parameters key-value pair, also handled the case where the value is an array. 
Ref: #62 
Next steps:
> Search parameters support for plugin

- docs/plugin_options.md
- docs/search_parameters.md
> Add documentation for Search Parameters

- package.json
- src/gatsby-node.js
- tests/gatsby-starter-default/gatsby-config.js
- tests/gatsby-starter-default/package.json
- tests/gatsby-starter-default/src/components/Breadcrumbs.js
- tests/gatsby-starter-default/src/components/NewsItem.js
- tests/gatsby-starter-default/test.robot
- tests/gatsby-starter-default/yarn.lock
- yarn.lock
References #95 
This is initial PR to handle just images. I had a doubt though, we only seem to be considering nodes of type `PloneNewsItem` handle as file nodes when required, don't we need to add type `PloneImage` also to this? @datakurre @cekk
> Image handling

- docs/file_handling.md
> Add file-handling docs

- src/gatsby-node.js
Fixes https://github.com/collective/gatsby-source-plone/pull/123
> Children batching

- src/gatsby-node.js
> Add comment for why mediaType is  text/html

- docs/tutorial/3_page_creation.md
Follow up to: https://github.com/collective/gatsby-starter-plone/pull/4
> Page creation docs

- docs/reference/navigation.md
- docs/tutorial/5_navigation.md
Covers Navbar and Breadcrumbs
Ref: #112
> Add narrative documentation for navigation

- src/gatsby-node.js
Earlier I removed expansions configuration, because I figured that navigation and breadcrumbs should always be fetched to update them properly (especially with incremental builds). I removed configurable expansions to ease that work.
This should restore expansions configuration option, which is important especially for fetching custom expansion data.
> Restore expansions configuration

- src/gatsby-node.js
This will solve the problem of fetching private mode images from plone site.
> Adding header to createRemoteFileNode

- package-lock.json
- package.json
- src/gatsby-node.js
Made modification after merging pr in Gatsby organization.
> Adding header for fetching private image

- mock-Server/package-lock.json
- mock-Server/package.json
- mock-Server/server.js
- src/gatsby-node.js
@datakurre I successfully tested this. I am able to send the data from the server and received from the gatsby-node.js. What should be my next step? I am thinking that If I am able to know What to send from WebSocket Server I will start working on adding node :)
> Adding mock-server

- tests/gatsby-starter-default/package.json
- tests/gatsby-starter-default/yarn.lock
@datakurre please! merge this. Earlier we only updated the root package.json to latest.
> Updating gatsby-source-filesystem to latest changes

- src/gatsby-node.js
- tests/gatsby-starter-default/gatsby-config.js
Related to #180 
I will refactor all the code and squash all my commit into one once I am done with this feature. I just want to complete the POC of this feature.
> Add node for the added field

- src/gatsby-node.js
- tests/gatsby-starter-default/gatsby-config.js
Fixes https://github.com/collective/gatsby-source-plone/issues/185
> Creating Node for the modified Content

- src/gatsby-node.js
Related to #184 this is an initial commit
> Deleting deleted node, breadcrumbsNode and navigationNode

- src/__tests__/gatsby-node.tests.js
- src/gatsby-node.js
- src/utils.js
> Adding test for makeNavigationNode

- src/__tests__/gatsby-node.tests.js
- src/gatsby-node.js
- src/utils.js
> Adding test for breadcrumbsNode

- demo/package.json
- package.json
It seems that new babel required changes to keep javascript on built site working https://www.thebasement.be/updating-to-babel-7.4/
> Add babel runtime

- demo/robotlab/TestUpdates.ipynb
- demo/test-updates.robot
> Add more acceptance tests (#212)

- src/__tests__/gatsby-node.tests.js
- src/gatsby-node.js
- src/utils.js
> Adding test for fetchPloneNavigation

- src/__tests__/gatsby-node.tests.js
- src/gatsby-node.js
- src/utils.js
> Adding test for fetchPloneBreadcrumbs

- src/__tests__/gatsby-node.tests.js
- src/gatsby-node.js
- src/utils.js
Fixes #217 currently it is not passing but I am trying to make it pass. I will request you for review when It is fully working.
> Adding test for ploneNodeGenerator

- src/gatsby-node.js
@datakurre Fixes #224
Replacing foreach array method with simple for loop done the trick. I tested for all the method and it works as intended :)
> Replacing foreach array method with simple for loop

- README.md
- docs/reference/configuration.md
Fixes #230 
Please! comment if I am missing something.
> Adding documentation for config options provided by plugin

- src/gatsby-node.js
Fixes #227. The private internet service provider stops internet service. But my university network will be shut down tomorrow morning, I guess because there is no one present in university right now. I tested both pull request in my local environment they all are running fine.
> Refactoring code for modified event

- src/gatsby-node.js
> Refactoring deleteWebSocketEvent

- src/__tests__/utils.tests.js
- src/gatsby-node.js
- src/utils.js
> Changing custom Logging utility to reporter API

- src/gatsby-node.js
Fixes #203. I am not able to reconnect to the server after I restarted the Plone server by using
the command  ```make stop-backend start-backend```. I also see the same problem with the WebSocket plugin for chrome also. can you help where I am doing something wrong!
> Reconnecting the websocket
